// <auto-generated />
namespace Sistema_Locadora.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class ReCreateLocacao : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ReCreateLocacao));
        
        string IMigrationMetadata.Id
        {
            get { return "202002092229172_ReCreateLocacao"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
